CREATE TABLE CURRENCY(
    ID INT,
    CONSTRAINT CURRENCY_PK PRIMARY KEY (ID),
    CURRENCY_EMOJI VARCHAR UNIQUE,
    CURRENCY VARCHAR UNIQUE NOT NULL,
    BID INT,
    BID_DIFFERENCE INT,
    ASK INT,
    ASK_DIFFERENCE INT,
    UPDATE_DATE DATE
);